from flask import Flask, request, render_template, jsonify, send_file
import anthropic
import os
import pandas as pd
from dotenv import load_dotenv
from datetime import datetime

load_dotenv()
api_key = os.getenv("ANTHROPIC_API_KEY")

if api_key is None:
    raise ValueError("ERROR: No API key found")

app = Flask(__name__)
client = anthropic.Anthropic(api_key=api_key)
historia = []

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/chat', methods=['POST'])
def chat():
    wiadomosc = request.get_json().get('message', '')
    if not wiadomosc:
        return jsonify({'error': 'Empty message'}), 400
    
    historia.append({"role": "user", "content": wiadomosc})
    
    odpowiedz = client.messages.create(
        model="claude-3-5-sonnet-20241022",
        max_tokens=500,
        messages=historia
    )
    
    tresc = odpowiedz.content[0].text
    historia.append({"role": "assistant", "content": tresc})
    
    return jsonify({'response': tresc})

@app.route('/analizuj', methods=['POST'])
def analizuj():
    if 'file' not in request.files:
        return jsonify({'error': 'No file uploaded'}), 400
    
    plik = request.files['file']
    if not plik.filename.endswith('.csv'):
        return jsonify({'error': 'CSV file required'}), 400
    
    df = pd.read_csv(plik)
    
    prompt = f"Analyze this CSV data. Rows: {len(df)}, Columns: {len(df.columns)}. Columns: {', '.join(df.columns)}. First 3 rows: {df.head(3).to_string()}. Write a short summary."
    
    odpowiedz = client.messages.create(
        model="claude-3-5-sonnet-20241022",
        max_tokens=600,
        messages=[{"role": "user", "content": prompt}]
    )
    
    podsumowanie = odpowiedz.content[0].text
    
    nazwa_pliku = f"raport_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
    
    html = f"""<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>Report</title>
<style>body{{font-family:Arial;max-width:900px;margin:50px auto;padding:20px;background:#f5f5f5}}
.container{{background:white;padding:40px;border-radius:10px;box-shadow:0 2px 10px rgba(0,0,0,0.1)}}
h1{{color:#333;border-bottom:3px solid #6C63FF;padding-bottom:10px}}
.info{{background:#f8f9fa;padding:15px;border-radius:5px;margin:20px 0}}
.summary{{background:#f8f9fa;padding:20px;border-radius:5px;margin:20px 0;line-height:1.6;white-space:pre-wrap}}
.footer{{margin-top:30px;color:#999;font-size:12px;text-align:center}}
</style></head>
<body><div class="container">
<h1>Data Analysis Report</h1>
<div class="info">File: {plik.filename}<br>Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}<br>Rows: {len(df)}<br>Columns: {len(df.columns)}</div>
<h2>AI Summary</h2>
<div class="summary">{podsumowanie}</div>
<div class="footer">Generated by Claude AI</div>
</div></body></html>"""
    
    with open(nazwa_pliku, 'w', encoding='utf-8') as f:
        f.write(html)
    
    return jsonify({
        'success': True,
        'filename': plik.filename,
        'rows': len(df),
        'columns': len(df.columns),
        'summary': podsumowanie,
        'report_file': nazwa_pliku
    })

@app.route('/pobierz/<filename>')
def pobierz(filename):
    return send_file(filename, as_attachment=True)

if __name__ == '__main__':
    app.run(debug=True, port=5000)
